/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProseRouteImport } from './routes/prose'
import { Route as ButtonsRouteImport } from './routes/buttons'
import { Route as IndexRouteImport } from './routes/index'

const ProseRoute = ProseRouteImport.update({
  id: '/prose',
  path: '/prose',
  getParentRoute: () => rootRouteImport,
} as any)
const ButtonsRoute = ButtonsRouteImport.update({
  id: '/buttons',
  path: '/buttons',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buttons': typeof ButtonsRoute
  '/prose': typeof ProseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buttons': typeof ButtonsRoute
  '/prose': typeof ProseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buttons': typeof ButtonsRoute
  '/prose': typeof ProseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/buttons' | '/prose'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/buttons' | '/prose'
  id: '__root__' | '/' | '/buttons' | '/prose'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ButtonsRoute: typeof ButtonsRoute
  ProseRoute: typeof ProseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/prose': {
      id: '/prose'
      path: '/prose'
      fullPath: '/prose'
      preLoaderRoute: typeof ProseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buttons': {
      id: '/buttons'
      path: '/buttons'
      fullPath: '/buttons'
      preLoaderRoute: typeof ButtonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ButtonsRoute: ButtonsRoute,
  ProseRoute: ProseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
