packages:
  - packages/**
  - apps/**
  - '!apps/next/.next/**'
allowBuilds:
  '@biomejs/biome': true
  '@parcel/watcher': true
  '@tailwindcss/oxide': true
  core-js: true
  esbuild: true
  lightningcss-cli: true
  sharp: true
  unrs-resolver: true
