import { AppBar } from '@/ui/components/app-bar'
import type { Metadata } from 'next'

import { Providers } from './providers'

// Global styles
import '../ui/styles/global.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="dark">
      <body className="antialiased">
        <Providers>
          <div className="layout-container">
            <AppBar />
            <main id="main-content">{children}</main>
          </div>
        </Providers>
      </body>
    </html>
  )
}
