import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'

/**
 * Core uikit styles including var system for breakpoints,
 * colors, scales, utils  etc., which can be optionally
 * integrated with Tailwind (colors, breakpoints etc.) via
 * Tailwind theme configuration.
 */
import '@infonomic/uikit/styles.css'

import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>{children}</body>
    </html>
  )
}
